version: '3.8'
services:
  php:
    image: syed855/my-yii2-php:8.2
    volumes:
      - /home/ubuntu/.composer-docker/cache:/cache
      - ./:/app:delegated
    ports:
      - "8000:80"
    networks:
      - default

networks:
  default:
    driver: overlay
