version: '3.8'

services:
  yii2-app:
    image: yiisoftware/yii2-php:8.2-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    networks:
      - yii2-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./ansible/nginx.conf.j2:/etc/nginx/conf.d/default.conf
    depends_on:
      - yii2-app
    networks:
      - yii2-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  yii2-network:
    driver: overlay
