version: '3.8'
services:
  php:
    image: syed855/my-yii2-php:8.2
    volumes:
      - C:/Users/HP/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
