global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['172.31.10.253:9100']
  - job_name: 'docker'
    static_configs:
      - targets: ['172.31.10.253:9323']
