---
- name: Deploy Yii2 application
  hosts: swarm
  become: yes

  vars:
    dockerhub_username: "syed855"
    dockerhub_password: "dubai@syed"
    image_name: "syed855/yii2-app:latest"
    service_name: "yii2-app"

  tasks:
    - name: Ensure python3-pip is installed
      apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: Install python3-jsondiff and python3-requests packages
      apt:
        name:
          - python3-jsondiff
          - python3-requests
        state: present
        update_cache: yes

    - name: Login to Docker Hub
      community.docker.docker_login:
        username: "{{ dockerhub_username }}"
        password: "{{ dockerhub_password }}"

    - name: Deploy or update service
      community.docker.docker_stack:
        name: "{{ service_name }}"
        state: present
        compose:
          - version: '3.8'
            services:
              app:
                image: "{{ image_name }}"
                ports:
                  - "8080:80"  # Changed port to avoid conflict
                deploy:
                  replicas: 1
                  update_config:
                    parallelism: 1
                    delay: 10s
                  restart_policy:
                    condition: on-failure
